/*
 * MPU60x0.c
 *
 *  Created on: 24-Jun-2021
 *      Author: ark
 */

#include "MPU60x0.h"
#include "stm32f446xx_i2c.h"

extern I2C_Handle_t I2C2Handle;


/*
 * @Descp : Wrapper function for I2C_MasterSenData
 *
 * @Params:
 *
 * @Note  :
 */
void MPU_Write(uint8_t *data, uint8_t count)
{
	I2C_MasterSendData( &I2C2Handle, data, count, MPU_ADDR);
}

/*
 * @Descp : Used specifically to send address
 *
 * @Params: The address code of the concerned register
 *
 * @Note  : NULL
 */
void MPU_SendAddress(uint8_t Addr)
{
	I2C_MasterSendData( &I2C2Handle, &Addr, 1, MPU_ADDR);
}

/*
 * @Descp : Wrapper for I2C_MasterReceiveData
 *
 * @Params:
 *
 * @Note  :
 */
void MPU_Read(uint8_t *data, uint8_t count)
{
	I2C_MasterReceiveData(&I2C2Handle, data, count, MPU_ADDR);
}

/*
 * @Descp : The Sample Rate for GYRO is generated by dividing the Gyro o/p rate by SMPLRT_DIV(divval)
 *  		Sample Rate = Gyro Output Rate /(1 + divval)
 *  		Gyro output rate = 8KHz when DLPF disabled else 1KHz
 *
 * @Params: any value from 0-255
 *
 * @Note  :	Accelerometer Sample Rate is 1KHz
 */
void MPU_Sample_Rate_Divider(uint8_t divval){
	MPU_SendAddress(SAMPLE_RATE_DIVIDER);
	MPU_Write(&divval, 1);
}


/*
 * @Descp : This is used to configure the DLPF(Digital Low Pass Filter)
 *
 * @Params: ConfigVal, any value between 0 - 7
 *
 * @Note  : NULL
 */
void MPU_Config_Register(uint8_t ConfigVal){
	MPU_SendAddress(CONFIG_REG);
	MPU_Write(&ConfigVal, 1);
}


/*
 * @Descp : Selects the  Full scale output of the Gyro sensor
 *
 * @Params: @GFscale
 *
 * @Note  : NULL
 */
void MPU_Gyro_FullScale_Selection(uint8_t Scale){
	MPU_SendAddress(GYRO_CONFIG);
	MPU_Write(&Scale, 1);
}


/*
 * @Descp : Selects the Full scale output of the Accelerometer sensor
 *
 * @Params: @AFScale
 *
 * @Note  : NULL
 */
void MPU_Accel_FullScale_Selection(uint8_t Scale){
	MPU_SendAddress(ACCEL_CONFIG);
	MPU_Write(&Scale, 1);
}


/*
 * @Descp : This register determines which sensor measurements are loaded into the FIFO buffer
 *
 * @Params: @FIFOEN
 *
 * @Note  : NULL
 */
void MPU_FIFO_Enable(uint8_t BitVal){			//Accepts bit values of the sensors, for which FIFO needs to be enabled
	MPU_SendAddress(FIFO_ENABLE);
	MPU_Write(&BitVal, 1);
}


/*
 * @Descp : This function configs the behavior of the interrupt signals at the INT pin
 *
 * @Params: @INTCONFIG
 *
 * @Note  : NULL
 */
void MPU_Interrupt_Pin_Config(uint8_t BitVal){
	MPU_SendAddress(INT_PIN_CONFIG);
	MPU_Write(&BitVal, 1);
}


/*
 * @Descp : Enables interrupt generation by interrupt sources
 *
 * @Params: @INTEN
 *
 * @Note  : NULL
 */
void MPU_Interrupt_Enable(uint8_t BitVal){
	MPU_SendAddress(INT_ENABLE);
	MPU_Write(&BitVal, 1);
}


/*
 * @Descp : Shows the status of the specified interrupt generating source
 *
 * @Params: @INTSTAT
 *
 * @Note  : Returns interrupt status of the corresponding flag of INT_STATUS register
 */
uint8_t MPU_Get_Interrupt_Status(uint8_t Flag){  	//Checks the given flag with the flag register of the InterruptStatus Register
	uint8_t temp = 0;

	MPU_SendAddress(INT_STATUS);
	MPU_Write(&Flag, 1);							//Send Flag code
	MPU_Read(&temp, 1);								//Read status

	return temp;
}


/*
 * @Descp :
 *
 * @Params:
 *
 * @Note  : NULL
 */
Cord_RegDef_t MPU_Get_Accel_value(void){
	//MPU_SendAddress();
}


/*
 * @Descp :
 *
 * @Params:
 *
 * @Note  : NULL
 */
Cord_RegDef_t MPU_Get_Gyro_value(void){
	//MPU_SendAddress();
}


/*
 * @Descp :
 *
 * @Params:
 *
 * @Note  : NULL
 */
Temp_RegDef_t MPU_Get_Temp(void){
	//MPU_SendAddress();
}


/*
 * @Descp :
 *
 * @Params:
 *
 * @Note  : NULL
 */
void MPU_Sig_Path_Reset(uint8_t whom_to_reset){
	MPU_SendAddress(SIG_PATH_RESET);
}


/*
 * @Descp :
 *
 * @Params:
 *
 * @Note  : NULL
 */
void MPU_User_Control(uint8_t BitVal){
	MPU_SendAddress(USER_CTRL);

}


/*
 * @Descp :
 *
 * @Params:
 *
 * @Note  : NULL
 */
void MPU_Power_Manager(uint8_t BitVal, uint8_t RegNo){
	if(RegNo == 1){
		MPU_SendAddress(PWR_MGMNT_1);

	}else if(RegNo == 2){
		MPU_SendAddress(PWR_MGMNT_2);

	}

}


/*
 * @Descp :
 *
 * @Params:
 *
 * @Note  : NULL
 */
uint16_t MPU_Get_FIFO_Count(void){
	//MPU_SendAddress();
}


/*
 * @Descp :
 *
 * @Params:
 *
 * @Note  : NULL
 */
uint8_t MPU_Get_FIFO_Data(void){
	MPU_SendAddress(FIFO_R_W);
}


/*
 * @Descp :
 *
 * @Params:
 *
 * @Note  : NULL
 */
uint8_t MPU_WHO_AM_I(void){
	uint8_t temp = 0;

	MPU_SendAddress(WHO_AM_I);
	MPU_Read(&temp,	1);

	return temp;
}


